### ISSUE TITLE
Bulk_extractor not generating report.xml with --regex option selected

### ISSUE THREAD

**Issue by jamiepb** [tw4l/brunnhilde#51] opened 2021-04-05 18:34 UTC
Hello,

I'm using Brunnhilde in the BitCurator environment in VirtualBox.When I run Brunnhilde on some files and have just -b flag or -b with --ssn_mode specified, I can find a report.xml file in the bulk_extractor folder that can be opened with Bulk Extractor Viewer. But if I run Brunnhilde with -b and --regex to a regex file, no report file appears. Additionally, all of the bulk extractor text files are blank which makes me think something went wrong with running bulk_extractor for other features too. Thank you for looking into it. 

Jamie

**Comment by kieranjol** [comment] 2021-04-06 09:51
What’s your regex that you’re using? I think that this might be a bulk
extractor issue rather than brunnhilde itself. It would be worth checking
if bulk extractor itself also produces reports with your regex. This
behaviour sounds similar to when I was using bulk extractor GUI within
bitcurator to create reports with a regex, but my regex just wasn’t getting
any hits and I was getting empty reports. When I eventually got the regex
correct , my reports had text again.

**Comment by jamiepb** [comment] 2021-04-08 22:54
I'm using the attached text file where I've compiled the regular expressions from the TOMES email NLP tagging project, from https://github.com/StateArchivesOfNorthCarolina/tomes-entities/tree/master/dictionaries/regexs/nc_gov. I commented out the SSN regex and URL regex which were giving me trouble (and redundant with bulk_extractor SSN scan anyway), but the rest seem to be working for me. I just ran the command "bulk_extractor -F /home/bcadmin/Desktop/findlist.txt -S ssn_mode=1 -R /media/sf_Processing_SA_/Processing/201808148 -o /home/bcadmin/Desktop/BE_reports/regexcl" in BitCurator and it product the reports, so it appears to work when I do it in BitCurator. 

[findlist.txt](https://github.com/tw4l/brunnhilde/files/6281969/findlist.txt)

**Comment by tw4l** [comment] 2021-04-09 01:49
Thanks for the report and the regex file, @jamiepb! I will try to reproduce on my end. What versions of BitCurator and Brunnhilde are you running? For brunnhilde you can check with `brunnhilde.py -V` or `brunnhilde.py --version`.

**Comment by jamiepb** [comment] 2021-04-09 13:06
I'm using brunnhilde 1.9.1 and Bitcurator 2.2.8 in Virtual Box. I did have to upgrade brunnhilde to be able to use the regex option, but I'm struggling to find which version exactly was included in BitCurator. It must have been 1.8 something.

**Comment by tw4l** [comment] 2021-04-09 14:33
@jamiepb Interesting, it works for me with the same versions of brunnhilde and BitCurator, using the following command:

```
brunnhilde.py -b --regex '/home/bcadmin/Desktop/bc-shared/TOMES_findlist.txt' '/home/bcadmin/Desktop/bc-shared/PII_test_data' /home/bcadmin/Desktop/ brun-out-be-regex-tomes
```

Feature files are created and I can see the results of the custom regex searches in `find.txt` and `lightgrep.txt`.

Do you maybe have an unescaped space in your command somewhere?

**Comment by jamiepb** [comment] 2021-04-19 12:39
Hi Tessa,

I’m sorry this falls into the category of “not sure what went wrong” or “user error somewhere,” but I tried it again and now the bulk extractor results do have a report.xml file and contents in the text files. I used the command

brunnhilde.py -b --ssn_mode 1 --regex /home/bcadmin/Desktop/findlist.txt /media/sf_Processing_SA_/Processing/201808148 -o /home/bcadmin/Desktop/brunnhilde/ssnandregex

Unfortunately I didn’t record the command from the first session that was giving me an error; it may have been a typo or maybe I had a network issue that caused the bulk extractor results to terminate. In any case, it seems to be working fine now. Thank you very much for your help on this!

Jamie

From: Tessa Walsh ***@***.***>
Sent: Friday, April 9, 2021 10:34 AM
To: tw4l/brunnhilde ***@***.***>
Cc: Patrick-Burns, Jamie A ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [tw4l/brunnhilde] Bulk_extractor not generating report.xml with --regex option selected (#51)

CAUTION: External email. Do not click links or open attachments unless you verify. Send all suspicious email as an attachment to Report ***@***.***>


@jamiepb<https://urldefense.com/v3/__https:/github.com/jamiepb__;!!HYmSToo!K5RmhcSoy8KIuhvId_y372FTLNpz418_iaqlWbuXYkOJdaVJW1MYwpTCCUqIcdF5S3MB1ImflA$> Interesting, it works for me with the same versions of brunnhilde and BitCurator, using the following command:

brunnhilde.py -b --regex '/home/bcadmin/Desktop/bc-shared/TOMES_findlist.txt' '/home/bcadmin/Desktop/bc-shared/PII_test_data' /home/bcadmin/Desktop/ brun-out-be-regex-tomes

Feature files are created and I can see the results of the custom regex searches in find.txt and lightgrep.txt.

Do you maybe have an unescaped space in your command somewhere?

**Comment by tw4l** [comment] 2021-04-19 16:02
No problem Jamie, I'm glad it's working for you! I'm closing this issue but feel free to re-open it if you experience unexpected behaviour again.

**Closed by tw4l** 2021-04-19 16:02 UTC
